apiVersion: v1
kind: ReplicationController
metadata:
  name: cidotnet-rc

spec:
  replicas: 2
  selector: 
    app: cidotnet-app
  template:
    metadata:
      labels:
        app: cidotnet-app
    spec:
      containers:
        - name: cidotnet-pod
          image: markaw/cidotnet-app
          ports:
            - containerPort: 80
