apiVersion: v1
kind: Service
metadata:
  name: cidotnet-svc
  labels:
    app: cidotnet-app

spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
  selector:
    app: cidotnet-app