version: '3.4'

services:
  cidotnetangularcalc:
    depends_on:
      - "cidotnetangularapp"
    image: markaw/cidotnet-api:latest
    ports:
      - "30003:80" 

  cidotnetangularapp:
    image: markaw/cidotnet-app:latest
    ports:
      - "30002:80" 

