name: CI-docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Net Core Api Docker image
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: markaw/cidotnet-api
          tags: latest
          dockerfile: ./Dockerfile
          
      - name: Build and push Angular App Docker image
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: markaw/cidotnet-app
          tags: latest        
          dockerfile: ./Dockerfile-angular
